// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("0c37bcbc-95ce-4a16-a922-27e3c7c2049a")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("ManagedGif.Tests")]
