//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagedGif {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManagedGif.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block type 0x{0:X2} not supported..
        /// </summary>
        internal static string BlockTypeNotSupported {
            get {
                return ResourceManager.GetString("BlockTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded value outside expected range..
        /// </summary>
        internal static string DecodedValueOutsideRange {
            get {
                return ResourceManager.GetString("DecodedValueOutsideRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading extension data..
        /// </summary>
        internal static string EndOfStreamExtensionData {
            get {
                return ResourceManager.GetString("EndOfStreamExtensionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading GIF extension identifier..
        /// </summary>
        internal static string EndOfStreamExtensionIdentifier {
            get {
                return ResourceManager.GetString("EndOfStreamExtensionIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading global color table..
        /// </summary>
        internal static string EndOfStreamGlobalColorTable {
            get {
                return ResourceManager.GetString("EndOfStreamGlobalColorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading compressed image data..
        /// </summary>
        internal static string EndOfStreamImageData {
            get {
                return ResourceManager.GetString("EndOfStreamImageData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading image descriptor..
        /// </summary>
        internal static string EndOfStreamImageDescriptor {
            get {
                return ResourceManager.GetString("EndOfStreamImageDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading local color table..
        /// </summary>
        internal static string EndOfStreamLocalColorTable {
            get {
                return ResourceManager.GetString("EndOfStreamLocalColorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading logical screen descriptor..
        /// </summary>
        internal static string EndOfStreamLogicalScreenDescriptor {
            get {
                return ResourceManager.GetString("EndOfStreamLogicalScreenDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream reading minimum code size..
        /// </summary>
        internal static string EndOfStreamMinimumCodeSize {
            get {
                return ResourceManager.GetString("EndOfStreamMinimumCodeSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected end of stream encountered reading GIF separator..
        /// </summary>
        internal static string EndOfStreamSeparator {
            get {
                return ResourceManager.GetString("EndOfStreamSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension 0x{0:X2} not supported..
        /// </summary>
        internal static string ExtensionNotSupported {
            get {
                return ResourceManager.GetString("ExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF header not found..
        /// </summary>
        internal static string HeaderNotFound {
            get {
                return ResourceManager.GetString("HeaderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring application extension with size {0}..
        /// </summary>
        internal static string IgnoringApplicationExtension {
            get {
                return ResourceManager.GetString("IgnoringApplicationExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignoring graphics control extension with size {0}..
        /// </summary>
        internal static string IgnoringGraphicsControlExtension {
            get {
                return ResourceManager.GetString("IgnoringGraphicsControlExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected count of pixel values reading compressed data..
        /// </summary>
        internal static string MismatchedPixelCount {
            get {
                return ResourceManager.GetString("MismatchedPixelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No color table for raster data..
        /// </summary>
        internal static string NoColorTable {
            get {
                return ResourceManager.GetString("NoColorTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected nonzero local color table size value..
        /// </summary>
        internal static string NonzeroLocalColorTableSizeValue {
            get {
                return ResourceManager.GetString("NonzeroLocalColorTableSizeValue", resourceCulture);
            }
        }
    }
}
